# Generated by Django 5.0 on 2026-01-06 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='is_3d_active',
            field=models.BooleanField(default=True, help_text='¿Mostrar botón Ver en 3D?'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='scale_factor',
            field=models.FloatField(default=1.0, help_text='Escala para el visor 3D'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
