# Generated by Django 5.0 to fix field type inconsistencies
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_furniture_created_at_furniture_description_and_more'),
    ]

    operations = [
        # Remove the old FileField columns
        migrations.RemoveField(
            model_name='furniture',
            name='image',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='model_3d',
        ),
        # Add the new CharField columns that match the current model
        migrations.AddField(
            model_name='furniture',
            name='image_path',
            field=models.CharField(
            max_length=255,
            null=True,
            blank=True,
            help_text='Ruta relativa a la imagen (ej: chair.jpg)',
    ),
),
        migrations.AddField(
            model_name='furniture',
            name='model_3d_path',
            field=models.CharField(
            max_length=255,
            null=True,
            blank=True,
            help_text='Ruta relativa al archivo 3D (ej: chair.glb)',
            validators=[django.core.validators.FileExtensionValidator(
            allowed_extensions=['glb', 'gltf']
        )],
    ),
),

    ]