# Generated by Django 6.0.1 on 2026-01-20 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_fix_model_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='model_3d_path',
            field=models.CharField(blank=True, help_text='Ruta relativa al archivo 3D (ej: chair.glb)', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf'])]),
        ),
    ]
