# Generated by Django 6.0.1 on 2026-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_furniture_model_3d_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='image_path',
            field=models.CharField(blank=True, default='default.jpg', help_text='Ruta relativa a la imagen (ej: chair.jpg)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='furniture',
            name='model_3d_path',
            field=models.CharField(blank=True, help_text='Ruta relativa al archivo 3D (ej: chair.glb)', max_length=255, null=True),
        ),
    ]
