# Generated by Django 6.0.1 on 2026-07-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_furniture_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.CharField(blank=True, help_text='Ruta relativa a la imagen (ej: category_salas.jpg)', max_length=255, null=True),
        ),
    ]
